services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lumen
      POSTGRES_USER: lumen_user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: